trigger:
- main

stages:
- stage: BatuhanTestStage
  displayName: "Batuhan Test Stage"
  jobs:
  - job: TestJob
    displayName: "Agentless Test Job"
    pool:
      vmImage: '' # Agentless işlemler için boş bırakılır
      name: 'Server' # Bu, agentless işlemleri işaret eder

      
